# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: nest.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='nest.proto',
  package='test.pb',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\nnest.proto\x12\x07test.pb\"k\n\x07GlobalA\x12$\n\x02na\x18\x01 \x01(\x0b\x32\x18.test.pb.GlobalA.NestedA\x12$\n\x02nb\x18\x02 \x01(\x0b\x32\x18.test.pb.GlobalB.NestedB\x1a\x14\n\x07NestedA\x12\t\n\x01s\x18\x01 \x01(\t\"k\n\x07GlobalB\x12$\n\x02nb\x18\x01 \x01(\x0b\x32\x18.test.pb.GlobalB.NestedB\x12$\n\x02na\x18\x02 \x01(\x0b\x32\x18.test.pb.GlobalA.NestedA\x1a\x14\n\x07NestedB\x12\t\n\x01s\x18\x01 \x01(\tb\x06proto3'
)




_GLOBALA_NESTEDA = _descriptor.Descriptor(
  name='NestedA',
  full_name='test.pb.GlobalA.NestedA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='test.pb.GlobalA.NestedA.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=110,
  serialized_end=130,
)

_GLOBALA = _descriptor.Descriptor(
  name='GlobalA',
  full_name='test.pb.GlobalA',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='na', full_name='test.pb.GlobalA.na', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='nb', full_name='test.pb.GlobalA.nb', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GLOBALA_NESTEDA, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=23,
  serialized_end=130,
)


_GLOBALB_NESTEDB = _descriptor.Descriptor(
  name='NestedB',
  full_name='test.pb.GlobalB.NestedB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='s', full_name='test.pb.GlobalB.NestedB.s', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=239,
)

_GLOBALB = _descriptor.Descriptor(
  name='GlobalB',
  full_name='test.pb.GlobalB',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='nb', full_name='test.pb.GlobalB.nb', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='na', full_name='test.pb.GlobalB.na', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[_GLOBALB_NESTEDB, ],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=132,
  serialized_end=239,
)

_GLOBALA_NESTEDA.containing_type = _GLOBALA
_GLOBALA.fields_by_name['na'].message_type = _GLOBALA_NESTEDA
_GLOBALA.fields_by_name['nb'].message_type = _GLOBALB_NESTEDB
_GLOBALB_NESTEDB.containing_type = _GLOBALB
_GLOBALB.fields_by_name['nb'].message_type = _GLOBALB_NESTEDB
_GLOBALB.fields_by_name['na'].message_type = _GLOBALA_NESTEDA
DESCRIPTOR.message_types_by_name['GlobalA'] = _GLOBALA
DESCRIPTOR.message_types_by_name['GlobalB'] = _GLOBALB
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GlobalA = _reflection.GeneratedProtocolMessageType('GlobalA', (_message.Message,), {

  'NestedA' : _reflection.GeneratedProtocolMessageType('NestedA', (_message.Message,), {
    'DESCRIPTOR' : _GLOBALA_NESTEDA,
    '__module__' : 'nest_pb2'
    # @@protoc_insertion_point(class_scope:test.pb.GlobalA.NestedA)
    })
  ,
  'DESCRIPTOR' : _GLOBALA,
  '__module__' : 'nest_pb2'
  # @@protoc_insertion_point(class_scope:test.pb.GlobalA)
  })
_sym_db.RegisterMessage(GlobalA)
_sym_db.RegisterMessage(GlobalA.NestedA)

GlobalB = _reflection.GeneratedProtocolMessageType('GlobalB', (_message.Message,), {

  'NestedB' : _reflection.GeneratedProtocolMessageType('NestedB', (_message.Message,), {
    'DESCRIPTOR' : _GLOBALB_NESTEDB,
    '__module__' : 'nest_pb2'
    # @@protoc_insertion_point(class_scope:test.pb.GlobalB.NestedB)
    })
  ,
  'DESCRIPTOR' : _GLOBALB,
  '__module__' : 'nest_pb2'
  # @@protoc_insertion_point(class_scope:test.pb.GlobalB)
  })
_sym_db.RegisterMessage(GlobalB)
_sym_db.RegisterMessage(GlobalB.NestedB)


# @@protoc_insertion_point(module_scope)
